// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvYZAe4iAht-8n-KCVw9xg0gWqKSQ_n48',
    appId: '1:1019732182215:web:c9616e6d93fc96fc6e6ae2',
    messagingSenderId: '1019732182215',
    projectId: 'attendance-app-3206f',
    authDomain: 'attendance-app-3206f.firebaseapp.com',
    storageBucket: 'attendance-app-3206f.appspot.com',
    measurementId: 'G-EK18GY2MPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxBwF_2pI99PKcHLlJR7XvjPzH0gmHZ1k',
    appId: '1:1019732182215:android:34083a857cae4a046e6ae2',
    messagingSenderId: '1019732182215',
    projectId: 'attendance-app-3206f',
    storageBucket: 'attendance-app-3206f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Q5aUPOywqstZpgBCxXGJ80dBiP0zmuk',
    appId: '1:1019732182215:ios:7d9521861a2e21a66e6ae2',
    messagingSenderId: '1019732182215',
    projectId: 'attendance-app-3206f',
    storageBucket: 'attendance-app-3206f.appspot.com',
    iosBundleId: 'com.example.attendanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Q5aUPOywqstZpgBCxXGJ80dBiP0zmuk',
    appId: '1:1019732182215:ios:7d9521861a2e21a66e6ae2',
    messagingSenderId: '1019732182215',
    projectId: 'attendance-app-3206f',
    storageBucket: 'attendance-app-3206f.appspot.com',
    iosBundleId: 'com.example.attendanceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvYZAe4iAht-8n-KCVw9xg0gWqKSQ_n48',
    appId: '1:1019732182215:web:7dd0d19e5856d3336e6ae2',
    messagingSenderId: '1019732182215',
    projectId: 'attendance-app-3206f',
    authDomain: 'attendance-app-3206f.firebaseapp.com',
    storageBucket: 'attendance-app-3206f.appspot.com',
    measurementId: 'G-06JVR1Y1YV',
  );
}
